


### DELETE for NAVOYGH

DELETE http://localhost:4004/odata/v4/nautical/NAVOYGH/1000004
### GET for NAVOYGH

GET http://localhost:4004/odata/v4/nautical/NAVOYGH

### post for NAVOYGH
POST http://localhost:4004/odata/v4/nautical/NAVOYGH
Content-Type: application/json

{
    "VOYNO": 1001,
    "VOYNM": "BTP ",
    "VNOMTK": "",
    "REFDOC": "",
    "DOCIND": 0,
    "VESSN": "",
    "VIMO": "",
    "CHTYP": "",
    "CHPNO": "",
    "CURRKEYS": "",
    "FRTCO": 0.000,
    "VSTAT": "",
    "VOYTY": "",
    "CARTY": "",
    "CURR": "",
    "FREGHT": 0.000,
    "PARTY": "",
    "BIDTYPE": "",
    "FRCOST": "",
    "FRTU": "",
    "FRCOST_ACT": 0.000,
    "ZDELETE": "",
    "REF_VOYNO": ""
    
}
### GET req for NAVOYGIP

GET http://localhost:4004/odata/v4/nautical/NAVOYGIP

### POST request for Item level Table

POST http://localhost:4004/odata/v4/nautical/NAVOYGIP
Content-Type: application/json

{
    "VOYNO_VOYNO":1000001,
    "VLEGN": 1,
    "PORTC": "INBOM",
    "PORTN": "INVIK",
    "LOCNAM": "",
    "PDIST": 0.000,
    "VSPEED": 0.000,
    "PPDAYS": 0.000,
    "VSDAYS": 0.000,
    "VETAD": "2024-01-22",
    "VETAT": "20:23:22",
    "VETDD": "2024-01-22",
    "VETDT": "20:23:22",
    "VWEAD": 0.000,
    "PSTAT": "",
    "MATNR": "",
    "MAKTX": "",
    "CARGS": 108,
    "CARGU": "LUMSUM",
    "OTHCO": 0.000,
    "FRCOST": 0.000,
    "TOTCO": 0.000
    
}

